/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.totalController;
import java.awt.Color;
import java.util.UUID;
import java.util.Vector;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.scripts.JO;
import model.asociado;
import model.cuota;
import model.prestamo;

/**
 *
 * @author E304
 */
public class view1 extends javax.swing.JFrame {

    totalController totalp = new totalController();

    /**
     * Creates new form view1
     */
    public view1() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        //asignando datos quemados
        quemados();
        Listar();
    }

    Vector<cuota> cTemp = new Vector();
    asociado a_sel = new asociado();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_asociados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_prestamos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_plazo = new javax.swing.JTextField();
        txt_valorTotal = new javax.swing.JTextField();
        txt_interes = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        txt_Asociado = new javax.swing.JTextField();
        btn_proyectar = new javax.swing.JButton();
        btn_aprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_asociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Salario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_asociados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_asociadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_asociados);
        if (tbl_asociados.getColumnModel().getColumnCount() > 0) {
            tbl_asociados.getColumnModel().getColumn(0).setResizable(false);
            tbl_asociados.getColumnModel().getColumn(1).setResizable(false);
            tbl_asociados.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton1.setText("Buscar");

        tbl_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ncuota", "ValorCuota", "ValorPagar", "Saldo", "Pagar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_prestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_prestamosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_prestamos);
        if (tbl_prestamos.getColumnModel().getColumnCount() > 0) {
            tbl_prestamos.getColumnModel().getColumn(0).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(1).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(2).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(3).setResizable(false);
            tbl_prestamos.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel1.setText("Asociado");

        jLabel2.setText("Valor");

        jLabel3.setText("Plazo");

        jLabel4.setText("Interes");

        jLabel5.setText("ValorTotal");

        txt_valorTotal.setEnabled(false);

        txt_Asociado.setEnabled(false);

        btn_proyectar.setText("Proyectar");
        btn_proyectar.setEnabled(false);
        btn_proyectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proyectarActionPerformed(evt);
            }
        });

        btn_aprobar.setText("Aprobar");
        btn_aprobar.setEnabled(false);
        btn_aprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_plazo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Asociado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addComponent(btn_proyectar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_aprobar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Asociado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_plazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_proyectar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_aprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_asociadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_asociadosMouseClicked

        vaciar();
        a_sel = totalp.getList_asociados().get(tbl_asociados.getSelectedRow());
        txt_Asociado.setText(a_sel.getNombre());
        btn_proyectar.setEnabled(true);
        if (a_sel.getEstado().equals("sinPrestamo")) {
            stop(true);
        } else if (a_sel.getEstado().equals("conPrestamo")) {
            stop(false);
        }
        listar2(a_sel);


    }//GEN-LAST:event_tbl_asociadosMouseClicked

    private void btn_proyectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proyectarActionPerformed

        try {
            asociado a1 = totalp.getList_asociados().get(tbl_asociados.getSelectedRow());

            double valor = Double.parseDouble(txt_valor.getText());
            double interes = Double.parseDouble(txt_interes.getText());
            double plazo = Double.parseDouble(txt_plazo.getText());

            if (plazo >= 1 && plazo <= 48) {
                if (interes >= 1 && interes <= 8) {
                    double valorTotal = valor + (valor * interes / 100);
                    if ((4 * a1.getSalario()) > valorTotal) {
                        txt_valorTotal.setText(valorTotal + "");
                        double valorCuota = valorTotal / plazo;
                        prestamo p1 = new prestamo(
                                valor,
                                interes,
                                plazo,
                                a1
                        );

                        double valorPagar = Math.round(valorTotal - valorCuota);

                        totalp.cuotas((int) plazo, 0, valorPagar, Math.round(valorCuota), valorTotal, p1, cTemp);
                        a_sel = a1;
                        btn_aprobar.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(null, "El valor total excede 4 veces el salario del asociado");
                        block();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El interes debe estar entre 1 y 8 por ciento");
                    block();
                }
            } else {
                JOptionPane.showMessageDialog(null, "El plazo debe estar entre 1 y 48 meses");
                block();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error, revise sus datos");
        }


    }//GEN-LAST:event_btn_proyectarActionPerformed

    private void btn_aprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aprobarActionPerformed
        //para probar

        totalp.igualar(0, totalp.getList_prestamos(), cTemp);

        totalp.cambiarEst_prestamo(0, a_sel, "conPrestamo");
        listar2(a_sel);
        cTemp.clear();
        btn_aprobar.setEnabled(false);
        vaciar();
        stop(false);

    }//GEN-LAST:event_btn_aprobarActionPerformed

    private void tbl_prestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_prestamosMouseClicked
        int column = tbl_prestamos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbl_prestamos.getRowHeight();

        if (row < tbl_prestamos.getRowCount() && row >= 0 && column < tbl_prestamos.getColumnCount() && column >= 0) {
            Object value = tbl_prestamos.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("pagar") && boton.getText().equals("Pagar")) {
                    int opc = JOptionPane.showConfirmDialog(null, "Desea pagar la cuota", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    switch (opc) {
                        case 0:

                            cambiarEstado(0, Integer.parseInt(tbl_prestamos.getValueAt(row, 0) + ""), a_sel, boton);

//                            else if (!totalp.getList_prestamos().get(row - 1).isPagada()) {
//                                JOptionPane.showMessageDialog(null, "Debe pagar la anterior");
//                            }
                            break;
                        case 1:
                            System.out.println(row);
                            break;

                    }

                    //EVENTOS ELIMINAR
                }
            }

        }
    }//GEN-LAST:event_tbl_prestamosMouseClicked

    public void cambiarEstado(int i, int ncuota, asociado a1, JButton btn) {
        cuota actual = totalp.getList_prestamos().get(i);
        if (actual.getNcuota() == ncuota && actual.getPres1().getA1().getCodigo().equals(a1.getCodigo())) {
            if (actual.getNcuota() == 1) {
                btn.setText("Pagado");
                btn.setBackground(Color.green);
                btn.setEnabled(false);
                actual.setPagada(true);
            } else if (actual.getNcuota() > 1 && totalp.getList_prestamos().get(i - 1).isPagada()) {
                btn.setText("Pagado");
                btn.setBackground(Color.green);
                btn.setEnabled(false);
                actual.setPagada(true);
                totalp.ultimaCuota(0, a1, 0);
                listar2(a1);
            } else {
                JOptionPane.showMessageDialog(null, "Debe pagar la anterior");
                i = totalp.getList_prestamos().size();
            }

        }

        i++;
        if (i < totalp.getList_prestamos().size()) {
            cambiarEstado(i, ncuota, a1, btn);
        } else {

        }

    }

    public void block() {
        btn_aprobar.setEnabled(false);
        cTemp.clear();
    }

    public void stop(boolean b) {
        btn_proyectar.setEnabled(b);
        txt_plazo.setEnabled(b);
        txt_interes.setEnabled(b);
        txt_valor.setEnabled(b);
    }

    public void quemados() {
        totalp.getList_asociados().add(new asociado(UUID.randomUUID() + "", "Hector Herrera", 1000000, "sinPrestamo"));
        totalp.getList_asociados().add(new asociado(UUID.randomUUID() + "", "Daniela Osorio", 500000, "sinPrestamo"));
        totalp.getList_asociados().add(new asociado(UUID.randomUUID() + "", "José Chico", 1500000, "sinPrestamo"));
        totalp.getList_asociados().add(new asociado(UUID.randomUUID() + "", "Christian Castilla", 2500000, "sinPrestamo"));
        totalp.getList_asociados().add(new asociado(UUID.randomUUID() + "", "Tupac Lopez", 5350000, "sinPrestamo"));
        totalp.getList_asociados().add(new asociado(UUID.randomUUID() + "", "Indian Malah", 805000, "sinPrestamo"));
    }

    public void vaciar() {
        txt_Asociado.setText("");
        txt_interes.setText("");
        txt_plazo.setText("");
        txt_valor.setText("");
        txt_valorTotal.setText("");
        block();
    }

    public void Listar() {

        listar_asociados(
                totalp.getList_asociados().size(),
                0,
                (DefaultTableModel) tbl_asociados.getModel(),
                totalp.getList_asociados()
        );

    }

    public void listar2(asociado a1) {

        tbl_prestamos.setDefaultRenderer(Object.class, new render());

        listar_prestamos(
                totalp.getList_prestamos().size(),
                0,
                (DefaultTableModel) tbl_prestamos.getModel(),
                totalp.getList_prestamos(),
                a1
        );
    }

    public static void listar_asociados(int limit, int i, DefaultTableModel tb1, Vector<asociado> arr) {
        if (i == 0) {
            tb1.setNumRows(0);
        }

        tb1.addRow(new Object[]{
            arr.get(i).getCodigo(),
            arr.get(i).getNombre(),
            arr.get(i).getSalario()
        });

        //incremento
        i++;
        //repetir
        if (i < limit) {
            listar_asociados(limit, i, tb1, arr);
        }
    }

    public static void listar_prestamos(int limit, int i, DefaultTableModel tb1, Vector<cuota> arr, asociado a1) {

        if (i == 0) {
            tb1.setNumRows(0);
        }

        if (arr.size() > 0) {

            JButton btnPagar = new JButton((arr.get(i).isPagada()) ? "Pagada" : "Pagar");
            btnPagar.setName("pagar");
            btnPagar.setEnabled(!arr.get(i).isPagada());
            btnPagar.setBackground((arr.get(i).isPagada()) ? Color.green : Color.red);

            if (arr.get(i).getPres1().getA1().getCodigo().equals(a1.getCodigo())) {
                tb1.addRow(new Object[]{
                    arr.get(i).getNcuota(),
                    arr.get(i).getValorCuota(),
                    arr.get(i).getValorPagar(),
                    arr.get(i).getSaldo(),
                    btnPagar
                });
            }
        }
        //incremento
        i++;
        //repetir
        if (i < limit) {
            listar_prestamos(limit, i, tb1, arr, a1);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aprobar;
    private javax.swing.JButton btn_proyectar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_asociados;
    private javax.swing.JTable tbl_prestamos;
    private javax.swing.JTextField txt_Asociado;
    private javax.swing.JTextField txt_interes;
    private javax.swing.JTextField txt_plazo;
    private javax.swing.JTextField txt_valor;
    private javax.swing.JTextField txt_valorTotal;
    // End of variables declaration//GEN-END:variables
}
